{"status": "broken", "attachments": [{"source": "9c57a503-1397-4d1c-bf18-33a8b4c061a1-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "fcbacc35-3b97-4b81-92f9-eaee255b8ea4-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "be0d2124-2608-4992-87a3-6b6608a1f6c0-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331397783, "uuid": "dcad17bf-2c4d-4bc9-8696-ac158852495c", "historyId": "4ec29530cd256306fdfe3d9f169a8b2b", "start": 1560331397764, "fullName": "test_case_api#test_yu_e_select_no_merno", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-38: ordinal not in range(128)", "trace": "def test_yu_e_select_no_merno():\n    \n        print(\"----------------------------- 余额查询-不传MERNO -----------------------------\")\n        paths = \"/merchant/showBalance.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID}\n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam)\n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-38: ordinal not in range(128)\n\ntest_case_api.py:171: UnicodeEncodeError"}, "name": "test_yu_e_select_no_merno"}