{"status": "broken", "attachments": [{"source": "3e2f03f3-d773-4759-90a6-930aa5e48f1c-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "ec39814c-35f5-448d-a5f4-31fa3f0556f5-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "0f561c02-e204-4416-a052-274877a68812-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331397630, "uuid": "642250a4-ad60-4ac0-b81e-3470c0b62aad", "historyId": "27bd79bfb281849ced4dc18db8f977dd", "start": 1560331397541, "fullName": "test_case_api#test_picture_puload_2m", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-35: ordinal not in range(128)", "trace": "def test_picture_puload_2m():\n        print(\"----------------------------------图片上传超过2M------------------------------------\")\n        paths = \"/upload/image.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID}\n        files_jpg = {\"image\": (\"34231.jpg\", open(\"D:\\\\34231.jpg\", \"rb\"), \"image/jpg\", {})}\n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam, files_image=files_jpg)\n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-35: ordinal not in range(128)\n\ntest_case_api.py:121: UnicodeEncodeError"}, "name": "test_picture_puload_2m"}